### ISSUE TITLE
ci flake: kprobe_copyfd_test missing all expected events

### ISSUE THREAD

**Issue by willfindlay** [cilium/tetragon#247]
Just got a CI flake in https://github.com/cilium/tetragon/runs/7410818480?check_suite_focus=true#step:7:10985 where we are not seeing any of the expected events in kprobe_copyfd_test. // cc @tpapagian 

Here is the Tetragon json log from the test: [tetragon-json.zip](https://github.com/cilium/tetragon/files/9142224/tetragon-json.zip)

**Comment by tpapagian** [comment]
During the testing of https://github.com/cilium/tetragon/pull/235 I have seen that there are some issues with close system call and unfollowfd. I believe that this is also the case here. 

I am assigning it to myself.

**Comment by willfindlay** [comment]
@tpapagian just adding some more info here. I think something recent may have made this flake way more common. Just saw it again only a few CI runs later.

**Comment by tpapagian** [comment]
I believe https://github.com/cilium/tetragon/pull/235/commits/d6cdbaab549519f67e0d846c95dcfa04e496023c should fix this issue. So let's wait for https://github.com/cilium/tetragon/pull/235 to be merged.

**Comment by willfindlay** [comment]
@tpapagian it's not fixed :( here's another failure https://github.com/cilium/tetragon/runs/7469979029?check_suite_focus=true

**Comment by Forsworns** [comment]
I met this problem too... I guess the problem comes from: 

---

@willfindlay You add an event check in #240. So that the event checker would fail on misaligned events.

Take [this failure](https://github.com/cilium/tetragon/runs/7469979029?check_suite_focus=true#step:7:211) as an example.

The `pkg\sensors\tracing\kprobe_copyfd_test.go` initialize a `ProcessKprobeChecker` to trace krpobe events on `__x64_sys_read`. 

Sadly, Tetragon defines two tracepoint events `ProcessExec` and `ProcessExit` and traces them by default. Then the checker found captured events are `ProcessExec` (maybe from executable binaries like `contrib\tester-progs\dup-tester.c`). 

Maybe we should disable the default tracing during tests, or at least disable them in configuration file like `testdata\specs\copyfd-__fd_install.yaml.tmpl`?

---

I'm not sure since I didn't read the codes for event checkers in detail....  Just provide a possible reason for these failures

**Comment by willfindlay** [comment]
@Forsworns I think it's unrelated unforunately. This test has been flaky for ages, although recently we started seeing these flakes more frequently.

The changes you're referring to in the eventchecker are specifically related to kprobe argument types -- these don't change between runs, and so they would cause consistent failures rather than flakes. Also, we would have expected to see such argument mismatches show up in the logs of the failed runs.

**Comment by Forsworns** [comment]
@willfindlay Thanks, I rebased my PR and it passes tests now

**Comment by kkourt** [comment]
Now that this is closed, maybe is worth removing the copy fd test from the vmtest blacklist: https://github.com/cilium/tetragon/blob/9539556a7899067bda42bc93a039ef180daa4fc3/tools/split-tetragon-gotests/main.go#L53
